# Generated by Django 5.0.4 on 2024-05-02 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoriyalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Make', models.CharField(max_length=150)),
                ('Model', models.CharField(max_length=150)),
                ('Color', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='conf/')),
                ('kategoriya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avtosalon.kategoriyalar')),
            ],
        ),
    ]
