# Generated by Django 5.0.4 on 2024-05-02 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Avtosalon', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kategoriyalar',
            new_name='Categories',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='kategoriya',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='Color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='Make',
            new_name='make',
        ),
        migrations.RenameField(
            model_name='transport',
            old_name='Model',
            new_name='model',
        ),
    ]
